### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by interstar** [darius/ichbins#2]
This looks really cool. But I'm having trouble getting started.

I tried compiling and running my first program, which was 

```
    (define (cube x) (* x x x))
    (cube 8)
```
 
The c output looks like this (showing void run as that's what seems to be generated :   

```
void run (void **function, int bp) {
  if (function) goto *function;
  push (entag (a_char, 't'));
  push (nil);
  prim2_cons ();
  assert (var_Dt == sp);
  push (entag (a_char, 'f'));
  push (nil);
  prim2_cons ();
  assert (var_Df == sp);
  bp = sp + 1; goto proc_main;

proc_main: {
  assert (0 == sp - bp + 1);
  push (stack[var_8]);
  TAILCALL (proc_cube, 1);
}

proc_cube: {
  enum { arg_x };
  assert (1 == sp - bp + 1);
  push (stack[bp + arg_x]);
  push (stack[bp + arg_x]);
  push (stack[bp + arg_x]);
  TAILCALL (proc_S, 3);
}
}

```
Which produces these errors when I try to compile the C

```
test.c: In function ‘run’:
test.c:102:15: error: ‘var_8’ undeclared (first use in this function)
   push (stack[var_8]);
               ^
test.c:102:15: note: each undeclared identifier is reported only once for each function it appears in
test.c:112:3: error: label ‘proc_S’ used but not defined
   TAILCALL (proc_S, 3);


```

Maybe  I'm just missing something from the code I'm writing. Or maybe this doesn't quite work the way I'm thinking it works. But do you have any examples of very simple programs of this kind?

Cheers
   
Phil

**Comment by darius** [comment]
That was a very reasonable thing to try, given almost no documentation (sorry! -- though there is Overview.text). The error occurs because the language has no numbers or arithmetic at all, and the error takes this form because I was content to let your source-level errors turn into obscure errors from the C compiler. Ichbins thought '8' was a variable name.

The tests directory has dumb little examples in increasing order of size, and there's an examples dir too. But I have to admit this whole project is a curiosity I don't think I'll ever properly document. I'm working on a vaguely Smalltalk-like Lisp system now that does have actual numbers, though it hasn't yet settled down enough for a compiler.

**Comment by darius** [comment]
(And 'proc_S' is for the '*' function you tried to call.)

**Comment by interstar** [comment]
Ah ... that explains it then. :-)

I assume you aren't thinking of adding numbers and arithmetic any time soon?

**Comment by darius** [comment]
I did make a bigger descendant of this with not just numbers but Erlang-style processes and messaging (just within one virtual machine). I can upload it to github, but it was a dead end for me -- it'd make more sense to start from a higher-order language, if you're going to get fancier.

This project was a nice hack and a good learning experience but probably not a good approach to helping lots of others learn.

**Comment by interstar** [comment]
That sounds interesting. Does it still compile to C? 

(What I was looking for was a simple Lisp-like to C compiler that was simple enough to add a couple of my own features to  - basically a way to embed a bit of lower-level code that could compile straight to a restricted subset of C. 

Erlang-style  processes and messages would definitely be a plus though. :-)

**Comment by darius** [comment]
https://github.com/darius/elv just checked most of it in now; it won't yet run because it needs a compiled version of the compiler, which I guess means one more file, but I have to go out now.

It compiles to a VM with an interpreter in C, though it hasn't actually changed much from the direct-to-C compiler.

**Comment by darius** [comment]
OK, it's running and decluttered now! For what it's worth! More likely as inspiration than direct use, but at least there's not a lot of it to sort through.

**Comment by interstar** [comment]
Thanks a lot. I'm going to take a look over the next couple of days.
